version: '3'
services:
  web:
    build: .
    command: rails s -p 3000 -b '0.0.0.0'
    stdin_open: true
    tty: true
    volumes:
      - .:/app
      - bundle_data:/usr/local/bundle
    ports:
      - "3000:3000"

volumes:
  bundle_data:
